In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS 

In [3]:
arr = np.arange(1,12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr[0]

np.int64(1)

In [15]:
arr[5:12] # remember to use collen 

array([ 6,  7,  8,  9, 10, 11])

In [11]:
arr[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arr[0:12:2] # step comes in the last 

array([ 1,  3,  5,  7,  9, 11])

NUMPY INDEXING AND SLICING OF MATRIX 

In [2]:
arr = np.arange(1,31).reshape(6,5) 
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
arr [5,4] # to print a single element and the indexing starts with 0

np.int64(30)

In [23]:
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [26]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [29]:
arr[0] # this is to slice the mtrix row wise 

array([1, 2, 3, 4, 5])

In [30]:
arr[:,3] # this is to slice the matrix column wise 

array([ 4,  9, 14, 19, 24, 29])

BOOLEAN INDEXING

In [33]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
even = arr%2==0
even

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [36]:
arr = arr[even]
arr

array([12, 14, 16, 18, 20])