In [1]:
import numpy as np

ARITHEMETIC OPERATIONS

In [8]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [9]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [10]:
a1-a2

array([-5, -5, -5, -5, -5])

In [11]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [12]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
a1//a2

array([0, 0, 0, 0, 0])

In [14]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [15]:
a1%a2

array([1, 2, 3, 4, 5])

BROADCASTING

In [17]:
l =[10,20,30,40]
arr = np.array(l)

In [18]:
arr+10

array([20, 30, 40, 50])

In [20]:
arr= np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
arr *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

DEEP AND SHALLOW COPY

In [24]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
slice = a[0:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [32]:
a[4:6] *10

array([50, 60])

In [34]:
a # so as we can see there are no changes in the sliced part of the original array , this is the concept of shallow copy where the changes made in the sliced part does not affect the actual array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

so when you slice a portion of the array then that is stored in a different location.
so the changes made in the sliced portion will not affect the actual array.
but if we take the array and we make a copy of it and make chnages then the original array
will be modified. if we do not want modification then we do the following

In [35]:
a 
b = a

In [36]:
b[0]=23
b

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a #here we see the original array is changed 

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
c = np.arange(1,21)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
c
d= c.copy()

In [41]:
d[0]=23
d

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
c # here our original array remains the same

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATION

In [43]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [44]:
a

array([[1, 2],
       [3, 4]])

In [45]:
b

array([[5, 6],
       [7, 8]])

In [48]:
a@b# for matrix multiplication

array([[19, 22],
       [43, 50]])

In [49]:
np.dot(a,b) # for matrix multiplication

array([[19, 22],
       [43, 50]])

In [51]:
a.T # for transpose 

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

STACKING ARRAY - remember matrices cannot be stacked

In [55]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [57]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

SPLITTING ARRAY

In [62]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [67]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]