In [2]:
import numpy as np

  Basic Array Creations

In [4]:
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [10]:
np.array(a)

array([1. , 2. , 3.5])

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]] # because this is a list and it is a vector 
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l) # now this is an array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function 

In [55]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
arr = np.zeros((4,2)) #first it is rows then its columns 
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr = np.linspace(1,10,5) # here we give the range and the number of outputs we want and it accordingly adjusts the numbers to give linear space between them 
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
Random Generation Function 

In [4]:
  np.random.rand(10) # if there is only one bracket it is a vector , if there are 2 brackets then its a Matrix

array([0.3217048 , 0.26380301, 0.67482502, 0.00780724, 0.76218602,
       0.79018077, 0.49903147, 0.22556796, 0.79296328, 0.75370467])

In [32]:
np.random.randn(10) # rand- when we want values b/w 0 and 1 and randn- for values b/w -3 and 3

array([ 1.30446906, -1.46775411, -0.16346475, -0.78852675,  1.88178666,
        0.98061659, -0.57463369,  1.5534291 ,  2.49524372, -0.45029561])

In [6]:
np.random.randint(1,20,10)

array([ 4, 10, 13, 15,  5,  6, 12,  2, 15,  1], dtype=int32)

Array Attributes 

In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.shape

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods 

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum() # sum of all the elements 

np.int64(45)

In [43]:
np.sum(arr,axis =0) # gives us sum column wise 

array([12, 15, 18])

In [44]:
np.sum(arr,axis =1) # gives us the sum row wise 

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax()

np.int64(8)

In [49]:
arr.argmin()

np.int64(0)

Reshaping and Resizing 

In [51]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
arr= arr.reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])