In [4]:
#Create a NumPy array containing numbers from 10 to 50.
import numpy as np
a = np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
#Create a 3×3 matrix filled with only 7s.
b = np.ones((3,3))
b*7

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [12]:
#Create an array: Print:
#first element
#last element
#middle 3 elements

c = np.array([5,10,15,20,25])
print(f"The fist element is: {c[0]}")
print(f"The Last element is: {c[4]}")
print(f"The Middle 3 elements are : {c[1:4]}")

The fist element is: 5
The Last element is: 25
The Middle 3 elements are : [10 15 20]


In [21]:
d = np.arange(1,10).reshape(3,3)
d[1]

array([4, 5, 6])

In [19]:
d[:,2]

array([3, 6, 9])

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f"Addition: {a+b}")
print(f"Multiplication:{a*b}")

Addition: [5 7 9]
Multiplication:[ 4 10 18]


In [23]:
arr= np.arange(1,21)
even= arr%2==0
arr[even]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
#Q13.
#You have student marks stored in a NumPy array.
#How would you find:
#average marks
#highest marks
#lowest marks
marks = np.array([45,47,49,40,41])
avg = np.mean(marks)
print(avg)
high = np.max(marks)
low = np.min(marks)
print(high)
print(low)

44.4
49
40
